server:
  port: 9998

spring:
  application:
      name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务注册与发现，并为每个服务创建route
          lowerCaseServiceId: true # 创建的每个route的服务名转换成小写
      routes:
      - id: dongzhen_gateway
        uri: http://baidu.com
        order: 10
        predicates:
        - Path=/uzdz1/*
      - id: uzdz_gateway
        uri: http://github.com/
        order: 5 #如果命中多个route，则order最小的会被执行
        predicates:
        - Path=/uzdz1/*
        filters:
        - Authorize=true,uzdz
      - id: gateway
        uri: lb://user
        order: 1 #如果命中多个route，则order最小的会被执行
        predicates:
        - Path=/users/*
        filters:
        - StripPrefix=1


eureka:
  instance:
    instance-id: gateway
  client:
    service-url: {"defaultZone" : "http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/"}