server:
  port: 8082

spring:
  application:
    name: common

eureka:
  instance:
    instance-id: common
  client:
    service-url: {"defaultZone" : "http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/"}
