server:
  port: 8099

spring:
  application:
    name: client

eureka:
  instance:
    instance-id: client
    prefer-ip-address: true # SpringCloud Eureka Client IP注册\
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
info:
  name: client
  version: 0001

PUBLIC:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
