server:
  port: 9001

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/uzdz/simple-springcloud-config.git'
          search-paths: /{application}
          strict-host-key-checking: false
          force-pull: true
    bus:
      enabled: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost

eureka:
  instance:
    instance-id: config # 服务注册中心实例的主机名
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh